    export const monedas = [
  { "AED": "Dirham de Emiratos Árabes Unidos" },
  { "AFN": "Afgani Afgano" },
  { "ALL": "Lek Albanés" },
  { "AMD": "Dram Armenio" },
  { "ANG": "Florín de Antillas Neerlandesas" },
  { "AOA": "Kwanza Angoleño" },
  { "ARS": "Peso Argentino" },
  { "AUD": "Dólar Australiano" },
  { "AWG": "Florín Arubeño" },
  { "AZN": "Manat Azerbaiyano" },
  { "BAM": "Marco Convertible de Bosnia-Herzegovina" },
  { "BBD": "Dólar de Barbados" },
  { "BDT": "Taka Bangladesí" },
  { "BGN": "Lev Búlgaro" },
  { "BHD": "Dinar de Baréin" },
  { "BIF": "Franco Burundés" },
  { "BMD": "Dólar Bermudeño" },
  { "BND": "Dólar de Brunéi" },
  { "BOB": "Boliviano" },
  { "BRL": "Real Brasileño" },
  { "BSD": "Dólar de las Bahamas" },
  { "BTN": "Ngultrum Butanés" },
  { "BWP": "Pula Botsuano" },
  { "BYN": "Rublo Bielorruso" },
  { "BZD": "Dólar Beliceño" },
  { "CAD": "Dólar Canadiense" },
  { "CDF": "Franco Congoleño" },
  { "CHF": "Franco Suizo" },
  { "CLP": "Peso Chileno" },
  { "CNY": "Yuan Chino" },
  { "COP": "Peso Colombiano" },
  { "CRC": "Colón Costarricense" },
  { "CUP": "Peso Cubano" },
  { "CVE": "Escudo Caboverdiano" },
  { "CZK": "Corona Checa" },
  { "DJF": "Franco Yibutiano" },
  { "DKK": "Corona Danesa" },
  { "DOP": "Peso Dominicano" },
  { "DZD": "Dinar Argelino" },
  { "EGP": "Libra Egipcia" },
  { "ERN": "Nakfa Eritreo" },
  { "ETB": "Birr Etíope" },
  { "EUR": "Euro" },
  { "FJD": "Dólar Fiyiano" },
  { "FKP": "Libra de las Islas Malvinas" },
  { "FOK": "Corona Feroesa" },
  { "GBP": "Libra Esterlina" },
  { "GEL": "Lari Georgiano" },
  { "GGP": "Libra de Guernsey" },
  { "GHS": "Cedi Ghanés" },
  { "GIP": "Libra de Gibraltar" },
  { "GMD": "Dalasi Gambiano" },
  { "GNF": "Franco Guineano" },
  { "GTQ": "Quetzal Guatemalteco" },
  { "GYD": "Dólar Guyanés" },
  { "HKD": "Dólar de Hong Kong" },
  { "HNL": "Lempira Hondureña" },
  { "HRK": "Kuna Croata" },
  { "HTG": "Gourde Haitiano" },
  { "HUF": "Forinto Húngaro" },
  { "IDR": "Rupia Indonesia" },
  { "ILS": "Nuevo Shekel Israelí" },
  { "IMP": "Libra de Isla de Man" },
  { "INR": "Rupia India" },
  { "IQD": "Dinar Iraquí" },
  { "IRR": "Rial Iraní" },
  { "ISK": "Corona Islandesa" },
  { "JEP": "Libra de Jersey" },
  { "JMD": "Dólar Jamaiquino" },
  { "JOD": "Dinar Jordano" },
  { "JPY": "Yen Japonés" },
  { "KES": "Chelín Keniano" },
  { "KGS": "Som Kirguís" },
  { "KHR": "Riel Camboyano" },
  { "KID": "Dólar de Kiribati" },
  { "KMF": "Franco Comorense" },
  { "KRW": "Won Surcoreano" },
  { "KWD": "Dinar Kuwaití" },
  { "KYD": "Dólar de Islas Caimán" },
  { "KZT": "Tenge Kazajo" },
  { "LAK": "Kip Laosiano" },
  { "LBP": "Libra Libanesa" },
  { "LKR": "Rupia de Sri Lanka" },
  { "LRD": "Dólar Liberiano" },
  { "LSL": "Loti Lesotense" },
  { "LYD": "Dinar Libio" },
  { "MAD": "Dirham Marroquí" },
  { "MDL": "Leu Moldavo" },
  { "MGA": "Ariary Malgache" },
  { "MKD": "Denar Macedonio" },
  { "MMK": "Kyat Birmano" },
  { "MNT": "Tugrik Mongol" },
  { "MOP": "Pataca de Macao" },
  { "MRU": "Ouguiya Mauritana" },
  { "MUR": "Rupia de Mauricio" },
  { "MVR": "Rupia de Maldivas" },
  { "MWK": "Kwacha Malauí" },
  { "MXN": "Peso Mexicano" },
  { "MYR": "Ringgit Malayo" },
  { "MZN": "Metical Mozambicano" },
  { "NAD": "Dólar Namibio" },
  { "NGN": "Naira Nigeriana" },
  { "NIO": "Córdoba Nicaragüense" },
  { "NOK": "Corona Noruega" },
  { "NPR": "Rupia Nepalesa" },
  { "NZD": "Dólar Neozelandés" },
  { "OMR": "Rial Omaní" },
  { "PAB": "Balboa Panameño" },
  { "PEN": "Sol Peruano" },
  { "PGK": "Kina Papua Nueva Guinea" },
  { "PHP": "Peso Filipino" },
  { "PKR": "Rupia Pakistaní" },
  { "PLN": "Złoty Polaco" },
  { "PYG": "Guaraní Paraguayo" },
  { "QAR": "Rial Catarí" },
  { "RON": "Leu Rumano" },
  { "RSD": "Dinar Serbio" },
  { "RUB": "Rublo Ruso" },
  { "RWF": "Franco Ruandés" },
  { "SAR": "Rial Saudí" },
  { "SBD": "Dólar de Islas Salomón" },
  { "SCR": "Rupia de Seychelles" },
  { "SDG": "Libra Sudanesa" },
  { "SEK": "Corona Sueca" },
  { "SGD": "Dólar de Singapur" },
  { "SHP": "Libra de Santa Helena" },
  { "SLE": "Leone (nuevo) de Sierra Leona" },
  { "SLL": "Leone de Sierra Leona" },
  { "SOS": "Chelín Somalí" },
  { "SRD": "Dólar Surinamés" },
  { "SSP": "Libra Sursudanesa" },
  { "STN": "Dobra Santotomense" },
  { "SYP": "Libra Siria" },
  { "SZL": "Lilangeni Suazi" },
  { "THB": "Baht Tailandés" },
  { "TJS": "Somoni Tayiko" },
  { "TMT": "Manat Turcomano" },
  { "TND": "Dinar Tunecino" },
  { "TOP": "Paʻanga Tongano" },
  { "TRY": "Lira Turca" },
  { "TTD": "Dólar de Trinidad y Tobago" },
  { "TVD": "Dólar Tuvaluano" },
  { "TWD": "Nuevo Dólar Taiwanés" },
  { "TZS": "Chelín Tanzano" },
  { "UAH": "Grivna Ucraniana" },
  { "UGX": "Chelín Ugandés" },
  { "USD": "Dólar Estadounidense" },
  { "UYU": "Peso Uruguayo" },
  { "UZS": "Som Uzbeko" },
  { "VES": "Bolívar Venezolano" },
  { "VND": "Dong Vietnamita" },
  { "VUV": "Vatu Vanuatuense" },
  { "WST": "Tala Samoano" },
  { "XAF": "Franco CFA de África Central" },
  { "XCD": "Dólar del Caribe Oriental" },
  { "XDR": "Derechos Especiales de Giro (FMI)" },
  { "XOF": "Franco CFA de África Occidental" },
  { "XPF": "Franco CFP (Polinesia Francesa)" },
  { "YER": "Rial Yemení" },
  { "ZAR": "Rand Sudafricano" },
  { "ZMW": "Kwacha Zambiano" },
  { "ZWL": "Dólar Zimbabuense" }
];